# EDA

## Objectives
* To gain an understanding of the dataset's structure, statistical properties, and quality in order to continue with a proper predictive modelling.
* Define what I want to predict (which feature, basically).
* To have fun :D

## Libraries

In [1]:
# Data manipulation
import numpy as np
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Files and environment
import os
from dotenv import load_dotenv, dotenv_values

## Data Loading

In [2]:
# Get project root (one level above notebooks/)
ROOT_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))
os.chdir(ROOT_DIR)

# Load env variables
load_dotenv()

# Get .env variables
DATA_PATH = dotenv_values().get("DATA_PATH", "./data")

# Load dataset
df = pd.read_csv(os.path.join(DATA_PATH, "loan.csv"))

/tmp/ipykernel_61752/640732337.py:12: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(DATA_PATH, "loan.csv"))

## Structure

### Head and Tail

In [5]:
df.head().sort_index(axis=1)

,acc_now_delinq,addr_state,all_util,annual_inc,annual_inc_joint,application_type,collection_recovery_fee,collections_12_mths_ex_med,delinq_2yrs,desc,dti,dti_joint,earliest_cr_line,emp_length,emp_title,funded_amnt,funded_amnt_inv,grade,home_ownership,id,il_util,initial_list_status,inq_fi,inq_last_12m,inq_last_6mths,installment,int_rate,issue_d,last_credit_pull_d,last_pymnt_amnt,last_pymnt_d,loan_amnt,loan_status,max_bal_bc,member_id,mths_since_last_delinq,mths_since_last_major_derog,mths_since_last_record,mths_since_rcnt_il,next_pymnt_d,open_acc,open_acc_6m,open_il_12m,open_il_24m,open_il_6m,open_rv_12m,open_rv_24m,out_prncp,out_prncp_inv,policy_code,pub_rec,purpose,pymnt_plan,recoveries,revol_bal,revol_util,sub_grade,term,title,tot_coll_amt,tot_cur_bal,total_acc,total_bal_il,total_cu_tl,total_pymnt,total_pymnt_inv,total_rec_int,total_rec_late_fee,total_rec_prncp,total_rev_hi_lim,url,verification_status,verification_status_joint,zip_code
0,0.0,AZ,NaN,24000.0,NaN,INDIVIDUAL,0.00,0.0,0.0,Borrower added on 12/22/11 > I need to upgra...,27.65,NaN,Jan-1985,10+ years,NaN,5000.0,4975.0,B,RENT,1077501,NaN,f,NaN,NaN,1.0,162.87,10.65,Dec-2011,Jan-2016,171.62,Jan-2015,5000.0,Fully Paid,NaN,1296599,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,credit_card,n,0.00,13648.0,83.7,B2,36 months,Computer,NaN,NaN,9.0,NaN,NaN,5861.071414,5831.78,861.07,0.00,5000.00,NaN,https://www.lendingclub.com/browse/loanDetail....,Verified,NaN,860xx
1,0.0,GA,NaN,30000.0,NaN,INDIVIDUAL,1.11,0.0,0.0,Borrower added on 12/22/11 > I plan to use t...,1.00,NaN,Apr-1999,< 1 year,Ryder,2500.0,2500.0,C,RENT,1077430,NaN,f,NaN,NaN,5.0,59.83,15.27,Dec-2011,Sep-2013,119.66,Apr-2013,2500.0,Charged Off,NaN,1314167,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,car,n,117.08,1687.0,9.4,C4,60 months,bike,NaN,NaN,4.0,NaN,NaN,1008.710000,1008.71,435.17,0.00,456.46,NaN,https://www.lendingclub.com/browse/loanDetail....,Source Verified,NaN,309xx
2,0.0,IL,NaN,12252.0,NaN,INDIVIDUAL,0.00,0.0,0.0,NaN,8.72,NaN,Nov-2001,10+ years,NaN,2400.0,2400.0,C,RENT,1077175,NaN,f,NaN,NaN,2.0,84.33,15.96,Dec-2011,Jan-2016,649.91,Jun-2014,2400.0,Fully Paid,NaN,1313524,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,small_business,n,0.00,2956.0,98.5,C5,36 months,real estate business,NaN,NaN,10.0,NaN,NaN,3003.653644,3003.65,603.65,0.00,2400.00,NaN,https://www.lendingclub.com/browse/loanDetail....,Not Verified,NaN,606xx
3,0.0,CA,NaN,49200.0,NaN,INDIVIDUAL,0.00,0.0,0.0,Borrower added on 12/21/11 > to pay for prop...,20.00,NaN,Feb-1996,10+ years,AIR RESOURCES BOARD,10000.0,10000.0,C,RENT,1076863,NaN,f,NaN,NaN,1.0,339.31,13.49,Dec-2011,Jan-2015,357.48,Jan-2015,10000.0,Fully Paid,NaN,1277178,35.0,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,other,n,0.00,5598.0,21.0,C1,36 months,personel,NaN,NaN,37.0,NaN,NaN,12226.302212,12226.30,2209.33,16.97,10000.00,NaN,https://www.lendingclub.com/browse/loanDetail....,Source Verified,NaN,917xx
4,0.0,OR,NaN,80000.0,NaN,INDIVIDUAL,0.00,0.0,0.0,Borrower added on 12/21/11 > I plan on combi...,17.94,NaN,Jan-1996,1 year,University Medical Group,3000.0,3000.0,B,RENT,1075358,NaN,f,NaN,NaN,0.0,67.79,12.69,Dec-2011,Jan-2016,67.79,Jan-2016,3000.0,Current,NaN,1311748,38.0,NaN,NaN,NaN,Feb-2016,15.0,NaN,NaN,NaN,NaN,NaN,NaN,766.9,766.9,1.0,0.0,other,n,0.00,27783.0,53.9,B5,60 months,Personal,NaN,NaN,38.0,NaN,NaN,3242.170000,3242.17,1009.07,0.00,2233.10,NaN,https://www.lendingclub.com/browse/loanDetail....,Source Verified,NaN,972xx

In [6]:
df.tail().sort_index(axis=1)

,acc_now_delinq,addr_state,all_util,annual_inc,annual_inc_joint,application_type,collection_recovery_fee,collections_12_mths_ex_med,delinq_2yrs,desc,dti,dti_joint,earliest_cr_line,emp_length,emp_title,funded_amnt,funded_amnt_inv,grade,home_ownership,id,il_util,initial_list_status,inq_fi,inq_last_12m,inq_last_6mths,installment,int_rate,issue_d,last_credit_pull_d,last_pymnt_amnt,last_pymnt_d,loan_amnt,loan_status,max_bal_bc,member_id,mths_since_last_delinq,mths_since_last_major_derog,mths_since_last_record,mths_since_rcnt_il,next_pymnt_d,open_acc,open_acc_6m,open_il_12m,open_il_24m,open_il_6m,open_rv_12m,open_rv_24m,out_prncp,out_prncp_inv,policy_code,pub_rec,purpose,pymnt_plan,recoveries,revol_bal,revol_util,sub_grade,term,title,tot_coll_amt,tot_cur_bal,total_acc,total_bal_il,total_cu_tl,total_pymnt,total_pymnt_inv,total_rec_int,total_rec_late_fee,total_rec_prncp,total_rev_hi_lim,url,verification_status,verification_status_joint,zip_code
887374,0.0,CA,NaN,31000.0,NaN,INDIVIDUAL,0.0,0.0,0.0,NaN,28.69,NaN,Sep-2004,8 years,Office Assistant,10000.0,10000.0,B,RENT,36371250,NaN,f,NaN,NaN,0.0,332.10,11.99,Jan-2015,Jan-2016,332.10,Jan-2016,10000.0,Current,NaN,39102635,NaN,NaN,77.0,NaN,Feb-2016,9.0,NaN,NaN,NaN,NaN,NaN,NaN,7055.47,7055.47,1.0,1.0,debt_consolidation,n,0.0,14037.0,82.1,B5,36 months,Debt consolidation,0.0,25274.0,15.0,NaN,NaN,3971.88,3971.88,1027.35,0.0,2944.53,17100.0,https://www.lendingclub.com/browse/loanDetail....,Verified,NaN,905xx
887375,0.0,NJ,NaN,79000.0,NaN,INDIVIDUAL,0.0,0.0,0.0,NaN,3.90,NaN,Mar-1974,10+ years,Director of Maintenance,24000.0,24000.0,B,MORTGAGE,36441262,NaN,f,NaN,NaN,1.0,797.03,11.99,Jan-2015,Jan-2016,797.03,Jan-2016,24000.0,Current,NaN,39152692,26.0,29.0,NaN,NaN,Feb-2016,5.0,NaN,NaN,NaN,NaN,NaN,NaN,16933.26,16933.26,1.0,0.0,home_improvement,n,0.0,8621.0,84.5,B5,36 months,Home improvement,0.0,140285.0,23.0,NaN,NaN,9532.39,9532.39,2465.65,0.0,7066.74,10200.0,https://www.lendingclub.com/browse/loanDetail....,Verified,NaN,072xx
887376,0.0,TN,NaN,35000.0,NaN,INDIVIDUAL,0.0,0.0,0.0,NaN,30.90,NaN,Sep-2003,5 years,Radiologist Technologist,13000.0,13000.0,D,RENT,36271333,NaN,w,NaN,NaN,0.0,316.07,15.99,Jan-2015,Jan-2016,316.07,Jan-2016,13000.0,Current,NaN,38982739,NaN,NaN,84.0,NaN,Feb-2016,9.0,NaN,NaN,NaN,NaN,NaN,NaN,11155.50,11155.50,1.0,1.0,debt_consolidation,n,0.0,11031.0,61.3,D2,60 months,Debt consolidation,0.0,34178.0,22.0,NaN,NaN,3769.74,3769.74,1925.24,0.0,1844.50,18000.0,https://www.lendingclub.com/browse/loanDetail....,Verified,NaN,378xx
887377,0.0,MA,NaN,64400.0,NaN,INDIVIDUAL,0.0,1.0,1.0,NaN,27.19,NaN,Oct-2003,1 year,Painter,12000.0,12000.0,E,RENT,36490806,NaN,w,NaN,NaN,2.0,317.86,19.99,Jan-2015,Jan-2016,317.86,Jan-2016,12000.0,Current,NaN,39222577,22.0,22.0,NaN,NaN,Feb-2016,17.0,NaN,NaN,NaN,NaN,NaN,NaN,10447.31,10447.31,1.0,0.0,debt_consolidation,n,0.0,8254.0,30.6,E3,60 months,Debt consolidation,0.0,58418.0,20.0,NaN,NaN,3787.67,3787.67,2234.98,0.0,1552.69,27000.0,https://www.lendingclub.com/browse/loanDetail....,Source Verified,NaN,010xx
887378,0.0,FL,NaN,100000.0,NaN,INDIVIDUAL,0.0,0.0,0.0,NaN,10.83,NaN,Dec-2001,10+ years,Manager Hotel Operations Oasis,20000.0,20000.0,B,RENT,36271262,NaN,f,NaN,NaN,1.0,664.20,11.99,Jan-2015,Jan-2016,664.20,Jan-2016,20000.0,Current,NaN,38982659,NaN,NaN,110.0,NaN,Feb-2016,8.0,NaN,NaN,NaN,NaN,NaN,NaN,14110.94,14110.94,1.0,1.0,credit_card,n,0.0,33266.0,79.8,B5,36 months,Credit card refinancing,0.0,33307.0,10.0,NaN,NaN,7943.76,7943.76,2054.70,0.0,5889.06,41700.0,https://www.lendingclub.com/browse/loanDetail....,Verified,NaN,331xx

#### Conclusions

### Dimensions

In [7]:
df.shape

(887379, 74)

#### Conclusions

### df.info()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887379 entries, 0 to 887378
Data columns (total 74 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           887379 non-null  int64
 1   member_id                    887379 non-null  int64
 2   loan_amnt                    887379 non-null  float64
 3   funded_amnt                  887379 non-null  float64
 4   funded_amnt_inv              887379 non-null  float64
 5   term                         887379 non-null  object
 6   int_rate                     887379 non-null  float64
 7   installment                  887379 non-null  float64
 8   grade                        887379 non-null  object
 9   sub_grade                    887379 non-null  object
 10  emp_title                    835917 non-null  object
 11  emp_length                   842554 non-null  object
 12  home_ownership               887379 non-null  object
 13  annual_inc                   887375 non-null  float64
 14  verification_status          887379 non-null  object
 15  issue_d                      887379 non-null  object
 16  loan_status                  887379 non-null  object
 17  pymnt_plan                   887379 non-null  object
 18  url                          887379 non-null  object
 19  desc                         126026 non-null  object
 20  purpose                      887379 non-null  object
 21  title                        887226 non-null  object
 22  zip_code                     887379 non-null  object
 23  addr_state                   887379 non-null  object
 24  dti                          887379 non-null  float64
 25  delinq_2yrs                  887350 non-null  float64
 26  earliest_cr_line             887350 non-null  object
 27  inq_last_6mths               887350 non-null  float64
 28  mths_since_last_delinq       433067 non-null  float64
 29  mths_since_last_record       137053 non-null  float64
 30  open_acc                     887350 non-null  float64
 31  pub_rec                      887350 non-null  float64
 32  revol_bal                    887379 non-null  float64
 33  revol_util                   886877 non-null  float64
 34  total_acc                    887350 non-null  float64
 35  initial_list_status          887379 non-null  object
 36  out_prncp                    887379 non-null  float64
 37  out_prncp_inv                887379 non-null  float64
 38  total_pymnt                  887379 non-null  float64
 39  total_pymnt_inv              887379 non-null  float64
 40  total_rec_prncp              887379 non-null  float64
 41  total_rec_int                887379 non-null  float64
 42  total_rec_late_fee           887379 non-null  float64
 43  recoveries                   887379 non-null  float64
 44  collection_recovery_fee      887379 non-null  float64
 45  last_pymnt_d                 869720 non-null  object
 46  last_pymnt_amnt              887379 non-null  float64
 47  next_pymnt_d                 634408 non-null  object
 48  last_credit_pull_d           887326 non-null  object
 49  collections_12_mths_ex_med   887234 non-null  float64
 50  mths_since_last_major_derog  221703 non-null  float64
 51  policy_code                  887379 non-null  float64
 52  application_type             887379 non-null  object
 53  annual_inc_joint             511 non-null     float64
 54  dti_joint                    509 non-null     float64
 55  verification_status_joint    511 non-null     object
 56  acc_now_delinq               887350 non-null  float64
 57  tot_coll_amt                 817103 non-null  float64
 58  tot_cur_bal                  817103 non-null  float64
 59  open_acc_6m                  21372 non-null   float64
 60  open_il_6m                   21372 non-null   float64
 61  open_il_12m                  21372 non-null   float64
 62  open_il_24m                  21372 non-null   float64
 63  mths_since_rcnt_il           20810 non-null   float64
 64  total_bal_il                 21372 non-null   float64
 65  il_util                      18617 non-null   float64
 66  open_rv_12m                  21372 non-null   float64
 67  open_rv_24m                  21372 non-null   float64
 68  max_bal_bc                   21372 non-null   float64
 69  all_util                     21372 non-null   float64
 70  total_rev_hi_lim             817103 non-null  float64
 71  inq_fi                       21372 non-null   float64
 72  total_cu_tl                  21372 non-null   float64
 73  inq_last_12m                 21372 non-null   float64
dtypes: float64(49), int64(2), object(23)
memory usage: 501.0+ MB

#### Conclusions

### Column implicit types

In [12]:
for col in sorted(df.columns):
    print(f"{col}:")
    print(df[col].head())
    print(df[col].tail())
    unique_values = df[col].unique()
    print(unique_values[:int(len(unique_values)*0.95)])
    print("\n")

acc_now_delinq:
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: acc_now_delinq, dtype: float64
887374    0.0
887375    0.0
887376    0.0
887377    0.0
887378    0.0
Name: acc_now_delinq, dtype: float64
[ 0.  1. nan  2.  3.  5.  4.  6.]


addr_state:
0    AZ
1    GA
2    IL
3    CA
4    OR
Name: addr_state, dtype: object
887374    CA
887375    NJ
887376    TN
887377    MA
887378    FL
Name: addr_state, dtype: object
['AZ' 'GA' 'IL' 'CA' 'OR' 'NC' 'TX' 'VA' 'MO' 'CT' 'UT' 'FL' 'NY' 'PA'
 'MN' 'NJ' 'KY' 'OH' 'SC' 'RI' 'LA' 'MA' 'WA' 'WI' 'AL' 'CO' 'KS' 'NV'
 'AK' 'MD' 'WV' 'VT' 'MI' 'DC' 'SD' 'NH' 'AR' 'NM' 'MT' 'HI' 'WY' 'OK'
 'DE' 'MS' 'TN' 'IA' 'NE' 'ID']


all_util:
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: all_util, dtype: float64
887374   NaN
887375   NaN
887376   NaN
887377   NaN
887378   NaN
Name: all_util, dtype: float64
[  nan  40.1  57.9 ... 137.1 132.3 116.3]


annual_inc:
0    24000.0
1    30000.0
2    12252.0
3    49200.0
4    80000.0
Name: annual_inc, dtype: float64
887374     31000.0
887375     79000.0
887376     35000.0
887377     64400.0
887378    100000.0
Name: annual_inc, dtype: float64
[24000.   30000.   12252.   ... 57161.44 57145.   60463.08]


annual_inc_joint:
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: annual_inc_joint, dtype: float64
887374   NaN
887375   NaN
887376   NaN
887377   NaN
887378   NaN
Name: annual_inc_joint, dtype: float64
[      nan  71000.   100000.    77000.   117000.    94348.32 113314.
  61366.44 192000.    49748.    72000.    74684.    92000.   120000.
  65000.    70000.   425000.   140000.    83000.    87000.   340000.
 152000.    84000.   102000.   108000.   227000.   182000.   110486.
  88000.    95000.   137303.   122000.   179000.    86000.   107000.
  98000.   128000.   112900.    64748.    82000.   133000.   130000.
  89000.   162000.   111000.   118000.    49000.   150000.   132000.
  80000.    62151.   175000.    44600.    96300.   107240.    91000.
  58800.   165000.    51000.   185000.   156500.    85000.   117492.
  44500.    93000.    68712.   112194.   115000.    93450.    76000.
  74000.   144000.   106400.    70308.    83200.   103561.8   90000.
 123000.   148898.    72356.    76201.    55000.   141000.   103000.
 208000.    81000.   177000.    62000.    96000.   166000.    94000.
  54696.   183000.   224000.   106000.   146000.    58000.    52000.
 112000.   110000.   161200.    88500.   145000.   132600.    28000.
 500000.   104000.   149000.    72239.    84700.   125200.   182407.
  85500.    78200.   139198.01  70500.    73000.    66600.    78000.
 260000.   146500.   105000.   107700.   176000.    40034.    66098.
  44796.    96850.    52879.    99000.   161000.   155000.   121000.
  69930.    52640.    97000.    83456.   131000.   167731.   109000.
 214000.    59952.   136429.   270000.    44000.   134700.   151000.
 116000.   215000.    56000.    55200.    89600.    50064.    49322.
 113500.   170000.   154650.   126000.   195000.   189729.    63695.
  82300.    36000.   100487.    51990.    64500.    54000.   198000.
  75200.    37000.   148000.   162796.    56700.    89556.    41976.
  35820.    73500.   210000.   109440.    84740.   114000.   138000.
  64000.    52800.    81120.   102800.   116700.   111805.   104800.
 125000.   213500.    87552.   113000.    46000.    51750.   139000.
  63400.   239181.24 109500.   142518.   124500.   101000.    49926.
 134000.    57184.   140505.   166120.   113950.    62200.   109720.
 148800.   105365.44  73220.   139753.    53000.   124000.    82841.
  74038.64  75001.    40988.    59000.    50000.   103500.    81329.
  25142.    58750.    91465.    84524.04 147000.    46122.    68000.
 245000.    69500.   154000.   137400.    63000.   141200.   150296.8
 123400.    77600.   101771.   119500.   201750.    73036.   191300.
 135360.   221000.    46600.   115832.   106192.   178000.   126934.16
  61465.   135000.    71136.   142000.   157000.    75000.    32760.
 168472.    61000.   139694.26 161500.    41544.    45000.    84032.
 188000.   202700.   100350.   190000.    88400.    78816.    17950.
  40500.    66928.   101318.    67000.   213000.    73588.41 109800.
 375000.    72653.   127000.   179160.    80748.72  64800.   106892.
 118500.   189490.    46700.   133545.    18480.   169000.  ]


application_type:
0    INDIVIDUAL
1    INDIVIDUAL
2    INDIVIDUAL
3    INDIVIDUAL
4    INDIVIDUAL
Name: application_type, dtype: object
887374    INDIVIDUAL
887375    INDIVIDUAL
887376    INDIVIDUAL
887377    INDIVIDUAL
887378    INDIVIDUAL
Name: application_type, dtype: object
['INDIVIDUAL']


collection_recovery_fee:
0    0.00
1    1.11
2    0.00
3    0.00
4    0.00
Name: collection_recovery_fee, dtype: float64
887374    0.0
887375    0.0
887376    0.0
887377    0.0
887378    0.0
Name: collection_recovery_fee, dtype: float64
[  0.       1.11     2.09   ... 225.2124 510.6744 452.0034]


collections_12_mths_ex_med:
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: collections_12_mths_ex_med, dtype: float64
887374    0.0
887375    0.0
887376    0.0
887377    1.0
887378    0.0
Name: collections_12_mths_ex_med, dtype: float64
[ 0. nan  1.  2.  4.  3.  6. 16. 20.  5.  7. 10.]


delinq_2yrs:
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: delinq_2yrs, dtype: float64
887374    0.0
887375    0.0
887376    0.0
887377    1.0
887378    0.0
Name: delinq_2yrs, dtype: float64
[ 0.  2.  3.  1.  4.  6.  5.  8.  7.  9. 11. nan 13. 15. 10. 12. 17. 18.
 29. 24. 14. 21. 22. 19. 16. 30. 26. 20.]


desc:
0      Borrower added on 12/22/11 > I need to upgra...
1      Borrower added on 12/22/11 > I plan to use t...
2                                                  NaN
3      Borrower added on 12/21/11 > to pay for prop...
4      Borrower added on 12/21/11 > I plan on combi...
Name: desc, dtype: object
887374    NaN
887375    NaN
887376    NaN
887377    NaN
887378    NaN
Name: desc, dtype: object
['  Borrower added on 12/22/11 > I need to upgrade my business technologies.<br>'
 '  Borrower added on 12/22/11 > I plan to use this money to finance the motorcycle i am looking at. I plan to have it paid off as soon as possible/when i sell my old bike. I only need this money because the deal im looking at is to good to pass up.<br><br>  Borrower added on 12/22/11 > I plan to use this money to finance the motorcycle i am looking at. I plan to have it paid off as soon as possible/when i sell my old bike.I only need this money because the deal im looking at is to good to pass up. I have finished college with an associates degree in business and its takingmeplaces<br>'
 nan ...
 "  Borrower added on 02/04/14 > to combine cc's &amp; new house heater, personal loan from brother<br><br> Borrower added on 02/04/14 > pay cc's ,pay off house heater,repay brother<br>"
 "  Borrower added on 02/04/14 > the loan is intended to pay off the discover card, citi card and part of either the mandt or chase cards, thus reducing  the amount of interest I'm paying and shortening the time to pay off these cards.<br>"
 '  Borrower added on 02/04/14 > To consolidate debt<br>']


dti:
0    27.65
1     1.00
2     8.72
3    20.00
4    17.94
Name: dti, dtype: float64
887374    28.69
887375     3.90
887376    30.90
887377    27.19
887378    10.83
Name: dti, dtype: float64
[27.65  1.    8.72 ... 38.75 36.97 37.29]


dti_joint:
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: dti_joint, dtype: float64
887374   NaN
887375   NaN
887376   NaN
887377   NaN
887378   NaN
Name: dti_joint, dtype: float64
[  nan 13.85 16.4  15.4  22.76 17.07 25.44 19.22 25.28 21.76 14.63 11.74
 15.85 28.45 15.75 15.94 21.69 21.93 22.98  3.01 12.21 11.19 17.51 23.4
 16.06  6.44 18.49  9.23 28.9  19.17  9.73 32.21 13.67 13.81 15.11 14.39
 23.6  17.48 35.49  9.22 22.48 17.8  25.91 18.39 23.99 13.83 24.88  6.81
 20.61 25.08 18.16 31.01 21.37 15.91 39.5  15.36 17.18 16.39 11.12 21.01
 20.82 13.53  9.67 30.62 19.09 13.   14.6  16.08 12.99 20.22 32.99 14.65
 13.95 27.11 14.96 13.88  8.06 23.43 25.37 19.26 26.76 19.5   8.36  9.93
 21.04 16.65 12.92 29.29 12.62 33.52 15.5  18.71 22.65 22.56  7.01 25.35
 31.92 18.94 20.71 37.81 14.92 13.15  6.47 21.25  8.26 19.15 21.36 18.74
 28.6  21.03 20.2  32.61 21.43 24.41  9.29 19.06 23.89 23.07 14.83 12.18
 14.26  9.82 15.76 27.27 33.01 17.47 17.19  5.31 23.33 38.19  3.   27.07
 16.86 14.97 18.22 29.23 18.62 27.21 12.02 31.15 10.5  30.21 17.89 16.72
 11.06 29.49  9.84 31.4  12.41 11.83 23.08 11.29 10.15 22.33 22.5  11.92
 26.39 13.09 22.63 24.02  7.74 23.47 28.97 15.63 12.19  6.52 28.46 23.14
  7.87 25.05 18.31 18.46 23.37 23.26  8.92 31.23 25.77 11.85 14.59 19.78
 22.18 17.13  6.17 16.55 32.8  14.5  17.59 33.1  26.04 26.16 23.24 21.7
 11.53 30.34 16.17 24.09 22.9  39.3  33.14 28.67 26.64 15.25 10.55 24.58
  6.33 21.82 15.51 10.05 19.45 11.25 12.36 17.6  43.86 17.98 17.08 23.95
 23.5  26.   26.47 13.47 26.07 22.55  5.97 14.09 17.75 20.62  9.47 17.35
 20.65 21.22 33.45 13.68 20.12 15.32 17.4  11.04 12.33 13.44 13.89 30.42
  3.05 21.41 10.92 28.92 13.79 21.88 16.16 17.82 16.66 24.79 17.99 13.96
 18.66 20.16 20.31 21.98 14.52 13.18  9.58 21.14 15.26 10.32 12.51 10.81
 11.08 31.04 13.54 13.19 28.87 21.28 26.84 17.61 21.46 34.59 18.72 19.52
  8.74 14.3  19.77 30.78 11.17  9.27 27.12 30.13 10.52 13.69 15.39 18.26
 13.02 20.57 11.57 22.64 13.28 13.7  18.96 21.86 21.45 11.61 10.02 22.57
  6.49 21.48 33.3   8.56 11.47 16.19 23.74 17.23 18.07 15.23 24.98 17.22
 28.72 16.8  17.14 17.91 15.87 28.89  9.7  19.86  3.09 20.45 12.95 20.46
 13.14  7.46 10.3  30.04 11.38 25.3  20.91 13.9  15.16 29.07 34.13  5.
 12.78 30.1  23.77 12.   14.51 16.95 21.72 15.7  17.41  9.26 14.82 19.65
 16.61 20.76 19.51 12.45 19.72 18.45  6.2  14.75 13.48 11.33 32.5  10.88
 19.64 15.89 21.4  13.2  10.18 14.84 19.32  8.57 16.18 20.6  31.51 17.52
 26.45 10.21 25.2  22.32 10.48  6.97 22.62  4.55 18.73 17.9  20.78 12.14
 19.36 13.01 18.18 31.11  9.24  3.98 18.02  7.75 16.34  3.56 25.68 22.17
 19.46 28.63 25.54 25.94 23.23 18.89 21.91 17.71  6.66 28.44  5.43 14.36
 21.44 25.26  8.83 17.09  7.54 20.39 11.26 16.26 14.24 28.26 15.07 23.79
 15.78 12.94 27.85 10.31 26.93 34.81 13.24]


earliest_cr_line:
0    Jan-1985
1    Apr-1999
2    Nov-2001
3    Feb-1996
4    Jan-1996
Name: earliest_cr_line, dtype: object
887374    Sep-2004
887375    Mar-1974
887376    Sep-2003
887377    Oct-2003
887378    Dec-2001
Name: earliest_cr_line, dtype: object
['Jan-1985' 'Apr-1999' 'Nov-2001' 'Feb-1996' 'Jan-1996' 'Nov-2004'
 'Jul-2005' 'Jan-2007' 'Apr-2004' 'Sep-2004' 'Jan-1998' 'Oct-1989'
 'Jul-2003' 'May-1991' 'Sep-2007' 'Oct-1998' 'Aug-1993' 'Oct-2003'
 'Jan-2001' 'Nov-1997' 'Feb-1983' 'Jul-1985' 'Apr-2003' 'Jun-2001'
 'Feb-2002' 'Aug-1984' 'Nov-2006' 'Dec-1987' 'Nov-1981' 'Feb-1997'
 'Apr-2005' 'Oct-2007' 'Dec-2000' 'Apr-2007' 'Dec-2001' 'Jan-2003'
 'Mar-1994' 'Sep-1998' 'Jun-2004' 'Nov-1995' 'Jul-1999' 'Jun-1995'
 'Sep-1992' 'Jan-2002' 'Apr-1992' 'Oct-2006' 'May-2000' 'Dec-1998'
 'Dec-2004' 'Oct-2000' 'May-2002' 'May-2006' 'Jul-2002' 'Jul-2006'
 'May-1997' 'Oct-2005' 'Apr-1995' 'Oct-2002' 'Jan-2000' 'Apr-2000'
 'Dec-1994' 'Sep-2005' 'Dec-1984' 'Dec-1999' 'Nov-2003' 'Jun-1989'
 'Jun-2003' 'Oct-1996' 'May-2003' 'Jun-2002' 'Jun-2007' 'Dec-1996'
 'Feb-1984' 'Sep-2002' 'Jan-1986' 'May-1998' 'Jan-1997' 'Jun-2005'
 'Feb-1990' 'Mar-2004' 'Jul-1995' 'Aug-1994' 'Jun-1992' 'Mar-1997'
 'Apr-2006' 'Apr-1990' 'Aug-1999' 'Sep-2000' 'Feb-2001' 'Dec-1988'
 'Feb-1999' 'Dec-1991' 'Aug-2000' 'Oct-2004' 'Aug-2004' 'Feb-2005'
 'Nov-2005' 'Nov-2000' 'May-2007' 'Jan-1991' 'Jun-2000' 'Aug-2006'
 'Dec-2002' 'Jun-1993' 'Jun-2006' 'Feb-2004' 'Dec-1990' 'Mar-2000'
 'Feb-1995' 'Jul-2001' 'Apr-2002' 'Sep-2006' 'May-1999' 'Aug-1998'
 'Dec-2005' 'May-2004' 'Oct-2001' 'Jun-1983' 'Mar-1986' 'Apr-1980'
 'Jul-2004' 'Jul-2008' 'May-1996' 'Jan-2004' 'Nov-2002' 'Aug-2002'
 'Aug-2001' 'Mar-1991' 'Sep-1989' 'Sep-1994' 'Sep-2003' 'Sep-1999'
 'Aug-2005' 'Dec-1986' 'Nov-1998' 'Feb-2006' 'May-1994' 'Nov-2007'
 'Feb-1993' 'Nov-1991' 'May-2005' 'Dec-1973' 'May-2001' 'Mar-1990'
 'Mar-1996' 'Oct-1979' 'Jun-1981' 'Mar-2001' 'Apr-2001' 'Jun-1999'
 'Nov-1993' 'Jan-2006' 'Dec-1997' 'Nov-1994' 'Jul-1997' 'Oct-1991'
 'Jun-1994' 'Mar-2006' 'Sep-1996' 'Apr-1991' 'Jul-1993' 'Jan-1995'
 'Sep-1987' 'Mar-2003' 'Oct-1999' 'Jul-1996' 'Dec-2003' 'Aug-1988'
 'Jan-1992' 'Mar-1998' 'Feb-2007' 'Aug-1982' 'Mar-1995' 'Dec-1992'
 'Jul-1998' 'Jul-1989' 'May-1990' 'Jul-1994' 'Sep-2001' 'Mar-1984'
 'Aug-2003' 'Nov-1999' 'Mar-2007' 'Mar-2008' 'Apr-1994' 'Jan-2005'
 'Jul-1986' 'Aug-1990' 'May-1992' 'Jul-2000' 'Mar-1988' 'May-1983'
 'Apr-1993' 'Jul-1978' 'Feb-2000' 'Dec-1981' 'Mar-1992' 'Jan-1981'
 'Sep-1990' 'Jun-1998' 'May-1993' 'Nov-1996' 'Mar-2002' 'Jan-1988'
 'Aug-1997' 'Aug-1987' 'Aug-2008' 'Oct-1994' 'Oct-1986' 'Feb-1994'
 'Jun-1996' 'Feb-1998' 'Nov-2008' 'Apr-1998' 'Jul-1979' 'Jan-1993'
 'May-1987' 'Jul-1971' 'Aug-2007' 'Jun-1997' 'Mar-1980' 'Dec-2006'
 'Jul-2007' 'Oct-1995' 'Jul-1991' 'Jul-1992' 'Dec-1972' 'Dec-1993'
 'Jan-1999' 'Feb-2003' 'Apr-1997' 'Dec-1995' 'Apr-1996' 'Jul-1990'
 'Mar-1970' 'Nov-1984' 'Apr-1984' 'Jul-1984' 'Aug-1995' 'Mar-1999'
 'Sep-1988' 'Mar-1989' 'Mar-1987' 'Oct-1997' 'Dec-1980' 'Jan-1994'
 'Sep-1995' 'Mar-2005' 'Jan-1989' 'Feb-1992' 'Jan-1990' 'Nov-1990'
 'Mar-1969' 'Jun-1975' 'Mar-1985' 'Dec-2007' 'Oct-1993' 'Dec-1989'
 'Sep-1980' 'Jun-1988' 'May-1978' 'Apr-1973' 'Aug-1989' 'Oct-1990'
 'Sep-1991' 'Feb-1982' 'Feb-1987' 'Nov-1985' 'Jan-1984' 'Jul-1988'
 'May-2008' 'Oct-1985' 'Mar-1983' 'Aug-1991' 'Sep-1986' 'Jun-1990'
 'Feb-1986' 'Sep-1997' 'Jun-1984' 'Sep-1981' 'Apr-1986' 'Aug-1979'
 'Aug-1980' 'Nov-1992' 'Sep-1993' 'Jun-1987' 'Sep-1982' 'Aug-1992'
 'Aug-1985' 'Jul-1983' 'Jun-1991' 'Dec-1983' 'Jan-1987' 'Nov-1978'
 'Oct-1984' 'Aug-1996' 'Nov-1989' 'Sep-1976' 'Nov-1986' 'Oct-1987'
 'Sep-2008' 'May-1977' 'May-1986' 'Mar-1981' 'Jan-1983' 'Nov-1976'
 'Sep-1979' 'Oct-1983' 'Sep-1962' 'Jun-1985' 'May-1982' 'Feb-1988'
 'Oct-1992' 'Aug-1983' 'Jun-1973' 'Apr-1985' 'Oct-1988' 'Oct-1981'
 'Sep-1968' 'Jul-1974' 'Nov-1987' 'May-1995' 'Feb-1991' 'Nov-1988'
 'Mar-1993' 'Jun-2008' 'Jul-1980' 'Dec-1982' 'Mar-1975' 'Feb-1980'
 'Apr-1988' 'Dec-1979' 'Sep-1985' 'Sep-1971' 'Mar-1978' 'Feb-2008'
 'Aug-1978' 'Nov-1970' 'Jun-1979' 'Jun-1980' 'Apr-1989' 'Sep-1983'
 'Feb-1989' 'Nov-1983' 'Jun-1986' 'Oct-1982' 'Aug-1986' 'Oct-1980'
 'May-1988' 'Dec-1985' 'Jan-1982' 'Sep-1977' 'Dec-1976' 'Apr-1982'
 'May-1984' 'Apr-2008' 'Feb-1979' 'Jan-2008' 'Sep-1964' 'Jul-1987'
 'Jan-1978' 'May-1989' 'Oct-1977' 'Dec-1975' 'Feb-1985' 'Oct-2008'
 'Nov-1982' 'May-1975' 'May-1985' 'Feb-1971' 'Jun-1977' 'Apr-1981'
 'May-1979' 'Jan-1972' 'Sep-1967' 'Apr-1978' 'Feb-1965' 'Apr-1983'
 'Nov-1975' 'Jun-1967' 'Mar-1974' 'Jul-1972' 'Aug-1967' 'Apr-1971'
 'Sep-1984' 'May-1981' 'Dec-1970' 'Oct-1973' 'Jan-1971' 'Dec-1963'
 'Apr-1974' 'Jan-1980' 'Aug-1969' 'Apr-1975' 'Jul-1977' 'Mar-1977'
 'Nov-1969' 'Jan-1976' 'Mar-1982' 'Apr-1987' 'Dec-1969' 'May-1974'
 'Aug-1974' 'Jun-1972' 'Mar-1963' 'Nov-1979' 'Aug-1975' 'Sep-1974'
 'Aug-1981' 'May-1973' 'Sep-1973' 'Mar-1973' 'Dec-1977' 'Oct-1976'
 'Jan-1974' 'Jan-1970' 'Aug-1968' 'Feb-1976' 'Jan-1975' 'Oct-1972'
 'Dec-1974' 'Feb-1973' 'Nov-1965' 'Mar-1972' 'Jun-1982' 'Jun-1974'
 'May-1965' 'Jun-1971' 'Oct-1970' 'Apr-1976' 'Oct-1971' 'Apr-1977'
 'Sep-1978' 'Oct-1978' 'Oct-1954' 'Feb-1981' 'Jan-1977' 'Aug-1977'
 'Dec-1978' 'Aug-1976' 'Jun-1968' 'Jun-1978' 'Jun-1969' 'May-1980'
 'Jan-1979' 'Oct-1965' 'Nov-1974' 'Apr-1966' 'Jun-1976' 'Feb-1972'
 'May-1976' 'Mar-1968' 'Mar-1976' 'Jul-1970' 'Mar-1979' 'Jul-1976'
 'Jul-1982' 'Sep-1965' 'Apr-1967' 'Oct-1963' 'Feb-1970' 'Jul-1973'
 'Feb-1978' 'Nov-1971' 'Aug-1972' 'Jul-1975' 'Sep-1970' 'Jul-1981'
 'Oct-1964' 'Sep-1972' 'May-1970' 'May-1963' 'Feb-1969' 'Nov-1980'
 'Jul-1967' 'Apr-1970' 'Nov-1977' 'Nov-1966' 'May-1971' 'Apr-1979'
 'May-1972' 'Feb-1968' 'Jul-1964' 'Nov-1967' 'Apr-1964' 'Feb-1975'
 'Jun-1959' 'Sep-1956' 'Jun-1966' 'Jan-1946' 'Mar-1966' 'Jan-1963'
 'Dec-1950' 'Jul-1969' 'Jan-1968' 'Nov-1973' 'Jun-1970' 'Feb-1977'
 'Feb-1974' 'Jan-1973' 'Feb-1966' 'Dec-1961' 'Aug-1973' 'Aug-1970'
 'Sep-1969' 'Sep-1975' 'Dec-1968' 'Nov-1954' 'Oct-1969' 'Dec-1965'
 'Apr-1972' 'Nov-1972' 'Sep-1963' 'Apr-1969' 'Nov-1962' 'Oct-1967'
 'May-1967' 'Nov-1961' 'Feb-1967' 'Nov-1968' 'Oct-1975' 'Mar-1971'
 'Aug-1971' 'Dec-1966' 'Oct-1968' 'Oct-1974' 'Nov-1963' 'Apr-1968'
 'May-1969' 'Nov-1959' nan 'Oct-2010' 'Dec-2009' 'Nov-2010' 'Jan-2010'
 'Dec-2008' 'Sep-2009' 'Jul-2010' 'Jan-2009' 'May-2009' 'May-2010'
 'Sep-2010' 'Apr-2009' 'Nov-2009' 'Apr-2010' 'Mar-2009' 'Feb-2009'
 'Aug-2009' 'Oct-2009' 'Jun-2009' 'Jun-2010' 'Jul-2009' 'Feb-2010'
 'Mar-2010' 'Aug-2010' 'Jan-1961' 'Oct-1962' 'Jun-1964' 'Apr-1962'
 'Jan-1960' 'Sep-1966' 'Mar-1965' 'May-1968' 'Jul-1966' 'Dec-1956'
 'Dec-1971' 'Apr-1965' 'Jan-1964' 'Jul-1965' 'Jan-1965' 'Jan-1962'
 'Aug-1964' 'Jan-1969' 'Oct-1966' 'Jun-1962' 'Dec-1967' 'Oct-1960'
 'Jul-1962' 'Dec-1960' 'Jul-1960' 'Jun-1965' 'May-1966' 'Oct-1957'
 'Aug-1965' 'May-1960' 'Jan-1967' 'Nov-1953' 'Oct-1959' 'Jun-1963'
 'Mar-1967' 'Jul-1963' 'Nov-1960' 'Mar-1962' 'Mar-1964' 'Jul-1968'
 'Feb-1963' 'Jan-1966' 'Dec-1964' 'May-1964' 'Oct-1961' 'Aug-1960'
 'Mar-1960' 'Apr-1955' 'Sep-1959' 'Aug-1966' 'Jul-1955' 'Aug-1961'
 'Nov-1964' 'May-1953' 'Nov-1950' 'Nov-1955' 'Mar-1961' 'Feb-1957'
 'Aug-1963' 'Feb-1960' 'Sep-1960' 'Feb-1964' 'Dec-1951' 'Nov-1958'
 'Aug-1962' 'Oct-1958' 'May-1962' 'Mar-2011' 'Jun-2011' 'Dec-2010'
 'Oct-2011' 'Sep-2011' 'Jul-2011' 'Apr-2011' 'May-2011' 'Jan-2011'
 'Feb-2011' 'Aug-2011' 'Apr-1963' 'Nov-2011' 'Dec-1958' 'Jan-1958'
 'Jul-1959' 'Jan-1955' 'May-1959' 'Aug-1946' 'Apr-1961' 'Jun-1958'
 'Jul-1958' 'Jun-1960' 'Jan-1951' 'Dec-1962' 'Mar-1959' 'Aug-1958'
 'Jan-1959' 'Feb-1961' 'Sep-1957' 'Jun-1949' 'Jun-1961' 'Jan-1956'
 'Jan-1954' 'Jan-1957' 'Jan-1944' 'Oct-1950' 'Jan-1948' 'Jul-1961'
 'May-1958' 'Jan-1953']


emp_length:
0    10+ years
1     < 1 year
2    10+ years
3    10+ years
4       1 year
Name: emp_length, dtype: object
887374      8 years
887375    10+ years
887376      5 years
887377       1 year
887378    10+ years
Name: emp_length, dtype: object
['10+ years' '< 1 year' '1 year' '3 years' '8 years' '9 years' '4 years'
 '5 years' '6 years' '2 years' '7 years']


emp_title:
0                         NaN
1                       Ryder
2                         NaN
3         AIR RESOURCES BOARD
4    University Medical Group
Name: emp_title, dtype: object
887374                   Office Assistant
887375            Director of Maintenance
887376           Radiologist Technologist
887377                            Painter
887378    Manager Hotel Operations Oasis
Name: emp_title, dtype: object
[nan 'Ryder' 'AIR RESOURCES BOARD' ... 'BILL REPRESENTATIVE'
 'VP of Sales and BD' 'Hab. Tech']


funded_amnt:
0     5000.0
1     2500.0
2     2400.0
3    10000.0
4     3000.0
Name: funded_amnt, dtype: float64
887374    10000.0
887375    24000.0
887376    13000.0
887377    12000.0
887378    20000.0
Name: funded_amnt, dtype: float64
[ 5000.  2500.  2400. ... 30375. 24325. 32225.]


funded_amnt_inv:
0     4975.0
1     2500.0
2     2400.0
3    10000.0
4     3000.0
Name: funded_amnt_inv, dtype: float64
887374    10000.0
887375    24000.0
887376    13000.0
887377    12000.0
887378    20000.0
Name: funded_amnt_inv, dtype: float64
[ 4975.  2500.  2400. ... 31675. 31425. 29800.]


grade:
0    B
1    C
2    C
3    C
4    B
Name: grade, dtype: object
887374    B
887375    B
887376    D
887377    E
887378    B
Name: grade, dtype: object
['B' 'C' 'A' 'E' 'F' 'D']


home_ownership:
0    RENT
1    RENT
2    RENT
3    RENT
4    RENT
Name: home_ownership, dtype: object
887374        RENT
887375    MORTGAGE
887376        RENT
887377        RENT
887378        RENT
Name: home_ownership, dtype: object
['RENT' 'OWN' 'MORTGAGE' 'OTHER' 'NONE']


id:
0    1077501
1    1077430
2    1077175
3    1076863
4    1075358
Name: id, dtype: int64
887374    36371250
887375    36441262
887376    36271333
887377    36490806
887378    36271262
Name: id, dtype: int64
[ 1077501  1077430  1077175 ... 40542757 40786254 40594020]


il_util:
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN

#### Conclusions

### Null and empty values

In [13]:
df_nulls = df.isnull()
null_counts = pd.DataFrame({
    "col": df_nulls.columns,
    "null_count": df_nulls.sum(),
    "null_proportion": df_nulls.sum() / df.shape[0]
}).sort_values(by="null_count", ascending=False)
null_counts

,col,null_count,null_proportion
dti_joint,dti_joint,886870,0.999426
annual_inc_joint,annual_inc_joint,886868,0.999424
verification_status_joint,verification_status_joint,886868,0.999424
il_util,il_util,868762,0.979020
mths_since_rcnt_il,mths_since_rcnt_il,866569,0.976549
inq_fi,inq_fi,866007,0.975916
open_rv_24m,open_rv_24m,866007,0.975916
open_acc_6m,open_acc_6m,866007,0.975916
all_util,all_util,866007,0.975916
inq_last_12m,inq_last_12m,866007,0.975916
total_cu_tl,total_cu_tl,866007,0.975916
open_il_12m,open_il_12m,866007,0.975916
max_bal_bc,max_bal_bc,866007,0.975916
open_il_6m,open_il_6m,866007,0.975916
open_il_24m,open_il_24m,866007,0.975916
open_rv_12m,open_rv_12m,866007,0.975916
total_bal_il,total_bal_il,866007,0.975916
desc,desc,761353,0.857980
mths_since_last_record,mths_since_last_record,750326,0.845553
mths_since_last_major_derog,mths_since_last_major_derog,665676,0.750160
mths_since_last_delinq,mths_since_last_delinq,454312,0.511971
next_pymnt_d,next_pymnt_d,252971,0.285077
total_rev_hi_lim,total_rev_hi_lim,70276,0.079195
tot_cur_bal,tot_cur_bal,70276,0.079195
tot_coll_amt,tot_coll_amt,70276,0.079195
emp_title,emp_title,51462,0.057993
emp_length,emp_length,44825,0.050514
last_pymnt_d,last_pymnt_d,17659,0.019900
revol_util,revol_util,502,0.000566
title,title,153,0.000172
collections_12_mths_ex_med,collections_12_mths_ex_med,145,0.000163
last_credit_pull_d,last_credit_pull_d,53,0.000060
delinq_2yrs,delinq_2yrs,29,0.000033
acc_now_delinq,acc_now_delinq,29,0.000033
earliest_cr_line,earliest_cr_line,29,0.000033
open_acc,open_acc,29,0.000033
pub_rec,pub_rec,29,0.000033
inq_last_6mths,inq_last_6mths,29,0.000033
total_acc,total_acc,29,0.000033
annual_inc,annual_inc,4,0.000005
member_id,member_id,0,0.000000
id,id,0,0.000000
sub_grade,sub_grade,0,0.000000
grade,grade,0,0.000000
installment,installment,0,0.000000
int_rate,int_rate,0,0.000000
term,term,0,0.000000
funded_amnt_inv,funded_amnt_inv,0,0.000000
funded_amnt,funded_amnt,0,0.000000
loan_amnt,loan_amnt,0,0.000000
total_rec_int,total_rec_int,0,0.000000
total_rec_prncp,total_rec_prncp,0,0.000000
issue_d,issue_d,0,0.000000
url,url,0,0.000000
purpose,purpose,0,0.000000
zip_code,zip_code,0,0.000000
addr_state,addr_state,0,0.000000
dti,dti,0,0.000000
home_ownership,home_ownership,0,0.000000
verification_status,verification_status,0,0.000000
total_pymnt_inv,total_pymnt_inv,0,0.000000
total_pymnt,total_pymnt,0,0.000000
out_prncp_inv,out_prncp_inv,0,0.000000
out_prncp,out_prncp,0,0.000000
initial_list_status,initial_list_status,0,0.000000
revol_bal,revol_bal,0,0.000000
pymnt_plan,pymnt_plan,0,0.000000
loan_status,loan_status,0,0.000000
policy_code,policy_code,0,0.000000
application_type,application_type,0,0.000000
collection_recovery_fee,collection_recovery_fee,0,0.000000
recoveries,recoveries,0,0.000000
total_rec_late_fee,total_rec_late_fee,0,0.000000
last_pymnt_amnt,last_pymnt_amnt,0,0.000000

### Conclusions

## Numerical

## Categorical

## Num vs Num

## Categ vs Categ

## Num vs Categ